
tap 'caskroom/cask'

install 'arduino'
install 'git'
install 'mercurial'
install 'tree'
install 'wget'
install 'zsh'
install 'zsh-completions'

cask install 'dropbox'
cask install 'firefox'
cask install 'flux'
cask install 'google-chrome'
cask install 'iterm2'
cask install 'licecap'
cask install 'slack'
cask install 'transmission'
cask install 'vlc'
