# Brewfile
# To install run `brew bundle`

# Install all apps in /Applications
cask_args appdir: '/Applications'


tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'


brew 'git'
brew 'docker'
brew 'gpg'
brew 'heroku'
brew 'httpie'
brew 'jq'
brew 'kubernetes-cli'
brew 'mercurial'
brew 'openssl'
brew 'mysql'
brew 'node'
brew 'postgresql'
brew 'python3'
brew 'rbenv'
brew 'sbt'
brew 'scala'
brew 'tree'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

cask 'alfred'
cask 'arduino'
cask 'atom'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'licecap'
cask 'minikube'
cask 'pgadmin3'
cask 'rescuetime'
cask 'slack'
cask 'sublime-text'
cask 'transmission'
cask 'vlc'
