#! /usr/bin/env bash


# ====================================================
#
# Dotfiles
#
# ----------------------------------------------------
#
# This kicks off the entire process of the dotfiles
# installation
#
# ====================================================

# Grab the config file
source $(pwd)/setup.cfg


# ==========================
#
# Setup some output functions
#
# ==========================
red=$'\e[1;31m'
pur=$'\e[0;35m'
yel=$'\e[0;33m'
grn=$'\e[0;32m'
end=$'\e[0m'

msg() {
  printf "${pur}> $*${end}\n"
}

success() {
  printf "${grn}$*${end}\n"
}

warn() {
  printf "${red}$*${end}\n"
}

don() {
  printf "...done\n\n"
}


# ==========================
#
# BEGIN
#
# ==========================


printf "\n\n${yel} _____     ______     ______   ______   __     __         ______     ______
/\\  __-.  /\\  __ \\   /\\__  _\\ /\\  ___\\ /\\ \\   /\\ \\       /\\  ___\\   /\\  ___\\
\\ \\ \\/\\ \\ \\ \\ \\/\\ \\  \\/_/\\ \\/ \\ \\  __\\ \\ \\ \\  \\ \\ \\____  \\ \\  __\\   \\ \\___  \\
 \\ \\____-  \\ \\_____\\    \\ \\_\\  \\ \\_\\    \\ \\_\\  \\ \\_____\\  \\ \\_____\\  \\/\\_____\\
  \\/____/   \\/_____/     \\/_/   \\/_/     \\/_/   \\/_____/   \\/_____/   \\/_____/${end}
                        ${pur}BEGINNING DOTFILES INSTALLATION${end}\n\n\n"

# ==========================
#
# First install Homebrew
#
# ==========================
msg "Installing Homebrew..."

# Only run on a Mac
if [ "$(uname -s)" == "Darwin" ]
then
  if [[ $(brew --version) ]]
  then
    success "Homebrew is already installed"
  else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    success "Homebrew was succesfully installed"
  fi
fi

# ==========================
#
# Now install the brew packages
#
# ==========================
if [[ $(brew --version) ]]
then
  msg "Running brew bundle"
  brew bundle
fi


# ==========================
#
# Now iterate through all the install.sh files
#
# ==========================
